# Generated by Django 4.1.1 on 2022-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=200)),
                ('aname', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=100)),
            ],
        ),
    ]
